### ISSUE TITLE
Update website docs now the help repo has issue templates

### ISSUE THREAD

**Issue by jstockwin** [jazzband-roadies/website#730]
https://github.com/jazzband-roadies/help/pull/197 has been merged, which closed https://github.com/jazzband-roadies/help/issues/188.

That said, we should update the website to tell users to select the correct template, rather than asking to apply labels.

**Comment by jstockwin** [comment]
(I will do this, feel free to assign me!)

**Comment by jezdez** [comment]
Thanks @jstockwin!
