### ISSUE TITLE
Add development server to docker compose?

### ISSUE THREAD

**Issue by jstockwin** [jazzband-roadies/website#738]
It's really nice that this has docker-compose set up, as it makes for a really nice development experience.

However, to test a change I just ran `docker-compose up web`, and I get an error because the `MAIL_PASSWORD` environment variable is not found. Obviously in this case I'm not interested in setting up emails, so it would be nice to not have to worry about it.

Perhaps we can somehow add a `dev` option to docker-compose so I can run the server without worrying about this?

What do you think?

**Comment by jezdez** [comment]
Yeah, good idea, lemme see what I can do..
